export interface VastuPada32 {
  code: string;
  nameHi: string;
  nameEn: string;
  startDeg: number;
  endDeg: number;
  centerDeg: number;
  isAuspicious: boolean;
  zone: 'E' | 'S' | 'W' | 'N';
  color: string;
  element: 'Jal' | 'Vayu' | 'Agni' | 'Prithvi' | 'Akash';
  elementNameHi: string;
  resultHi: string;
  resultEn: string;
  usageHi: string;
  usageEn: string;
}

export const VASTU_32_PADAS: VastuPada32[] = [
  // North (N3 to N8, N1 to N2) — Water / Wealth & Career
  {
    code: 'N3*',
    nameHi: 'मुख्य',
    nameEn: 'Mukhya',
    startDeg: 0,
    endDeg: 11.25,
    centerDeg: 5.625,
    isAuspicious: true,
    zone: 'N',
    color: '#065F46',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: '★ श्रेष्ठ द्वार — अकूत धन, सुख, समृद्धि व व्यावसायिक सफलता',
    resultEn: 'Highly Auspicious — Immense wealth, prosperity & business victory',
    usageHi: 'मुख्य द्वार, तिजोरी, बैठक, जल स्थापना',
    usageEn: 'Main Entrance, Safe/Treasury, Living Room, Water'
  },
  {
    code: 'N4*',
    nameHi: 'भल्लाट',
    nameEn: 'Bhallat',
    startDeg: 11.25,
    endDeg: 22.5,
    centerDeg: 16.875,
    isAuspicious: true,
    zone: 'N',
    color: '#065F46',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: '★ कुबेर द्वार — अटूट संपत्ति, वंश वृद्धि व ऐश्वर्य',
    resultEn: 'Kubera Gate — Massive abundance, legacy & royal fortune',
    usageHi: 'मुख्य द्वार, कैश लॉकर, मुख्य कक्ष',
    usageEn: 'Main Gate, Cash Vault, Master Suite'
  },
  {
    code: 'N5',
    nameHi: 'सोम',
    nameEn: 'Soma',
    startDeg: 22.5,
    endDeg: 33.75,
    centerDeg: 28.125,
    isAuspicious: false,
    zone: 'N',
    color: '#1E293B',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: 'धार्मिक प्रवृत्ति, अध्यात्म लाभ; परंतु द्वार से अत्यधिक व्यय संभव',
    resultEn: 'Spiritual upliftment; entrance may cause excessive expenses',
    usageHi: 'ध्यान, पूजा, अध्ययन कक्ष',
    usageEn: 'Meditation, Prayer Room, Study'
  },
  {
    code: 'N6',
    nameHi: 'भुजंग',
    nameEn: 'Bhujaga',
    startDeg: 33.75,
    endDeg: 45,
    centerDeg: 39.375,
    isAuspicious: false,
    zone: 'N',
    color: '#1E293B',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: 'शत्रु भय व गुप्त चिंताएं; औषधि व ध्यान हेतु उत्तम',
    resultEn: 'Caution for entrance; ideal for healing & medical storage',
    usageHi: 'दवाइयां, चिकित्सा, जल संग्रह',
    usageEn: 'Medicine, Healing, Water Storage'
  },
  {
    code: 'N7',
    nameHi: 'अदिति',
    nameEn: 'Aditi',
    startDeg: 45,
    endDeg: 56.25,
    centerDeg: 50.625,
    isAuspicious: false,
    zone: 'N',
    color: '#162C48',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: 'कन्या संतान की उन्नति; द्वार से मानसिक अशांति संभव',
    resultEn: 'Feminine grace; entrance may cause restlessness',
    usageHi: 'योग, ध्यान, खुला बरामदा',
    usageEn: 'Yoga, Open Balcony, Relaxation'
  },
  {
    code: 'N8',
    nameHi: 'दिति',
    nameEn: 'Diti',
    startDeg: 56.25,
    endDeg: 67.5,
    centerDeg: 61.875,
    isAuspicious: false,
    zone: 'N',
    color: '#162C48',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: 'दूरदृष्टि व बौद्धिक चिंतन; द्वार से अनावश्यक खर्च',
    resultEn: 'Broad vision & clarity; entrance causes financial drain',
    usageHi: 'पुस्तकालय, कला कक्ष, शांति क्षेत्र',
    usageEn: 'Library, Arts, Calm Zone'
  },

  // East (E1 to E8) — Air/Wood / Growth, Vitality & Social Status
  {
    code: 'E1',
    nameHi: 'शिखी',
    nameEn: 'Shikhi',
    startDeg: 67.5,
    endDeg: 78.75,
    centerDeg: 73.125,
    isAuspicious: false,
    zone: 'E',
    color: '#3B1F05',
    element: 'Vayu',
    elementNameHi: 'वायु/अग्नि तत्व',
    resultHi: 'अग्नि भय व दुर्घटना की आशंका; द्वार वर्जित',
    resultEn: 'Fire hazard risk; entrance is strictly prohibited',
    usageHi: 'पूजा, खुला आंगन, जल कुंड',
    usageEn: 'Temple, Open Courtyard, Water'
  },
  {
    code: 'E2',
    nameHi: 'पर्जन्य',
    nameEn: 'Parjanya',
    startDeg: 78.75,
    endDeg: 90,
    centerDeg: 84.375,
    isAuspicious: false,
    zone: 'E',
    color: '#3B1F05',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: 'अधिक व्यय व कन्या संतान बाहुल्य; जल व हरियाली हेतु शुभ',
    resultEn: 'Excessive expenditure; good for greenery & rainwater harvesting',
    usageHi: 'बगीचा, पौधे, जल स्रोत',
    usageEn: 'Garden, Greenery, Water Harvest'
  },
  {
    code: 'E3*',
    nameHi: 'जयंत',
    nameEn: 'Jayant',
    startDeg: 90,
    endDeg: 101.25,
    centerDeg: 95.625,
    isAuspicious: true,
    zone: 'E',
    color: '#065F46',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: '★ श्रेष्ठ द्वार — उत्साह, विजय, यश, सामाजिक प्रभाव व धन लाभ',
    resultEn: 'Highly Auspicious — Enthusiasm, victory, fame & social status',
    usageHi: 'मुख्य द्वार, ड्राइंग रूम, प्रवेश बरामदा',
    usageEn: 'Main Entrance, Drawing Room, Porch'
  },
  {
    code: 'E4*',
    nameHi: 'इंद्र',
    nameEn: 'Indra',
    startDeg: 101.25,
    endDeg: 112.5,
    centerDeg: 106.875,
    isAuspicious: true,
    zone: 'E',
    color: '#065F46',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: '★ राजकृपा द्वार — उच्च प्रशासनिक संबंध, मान-सम्मान व नेतृत्व',
    resultEn: 'Royal Favor Gate — Government influence, honors & leadership',
    usageHi: 'मुख्य द्वार, बैठक, कार्यालय',
    usageEn: 'Main Gate, Living Room, Home Office'
  },
  {
    code: 'E5',
    nameHi: 'सूर्य',
    nameEn: 'Surya',
    startDeg: 112.5,
    endDeg: 123.75,
    centerDeg: 118.125,
    isAuspicious: false,
    zone: 'E',
    color: '#2A1808',
    element: 'Vayu',
    elementNameHi: 'अग्नि/वायु तत्व',
    resultHi: 'क्रोध व उग्रता में वृद्धि; द्वार से आंतरिक कलह संभव',
    resultEn: 'Sharp temper & legal disputes; entrance causes agitation',
    usageHi: 'व्यायाम कक्ष, सूर्य स्नान, खुला बरामदा',
    usageEn: 'Gym, Sunlight Area, Open Verandah'
  },
  {
    code: 'E6',
    nameHi: 'सत्य',
    nameEn: 'Satya',
    startDeg: 123.75,
    endDeg: 135,
    centerDeg: 129.375,
    isAuspicious: false,
    zone: 'E',
    color: '#2A1808',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: 'वचनबद्धता; परंतु द्वार से व्यापार में धोखा मिलने का भय',
    resultEn: 'Truthfulness; entrance can bring broken promises & trade loss',
    usageHi: 'अध्ययन कक्ष, परामर्श कक्ष',
    usageEn: 'Study, Consultation, Library'
  },
  {
    code: 'E7',
    nameHi: 'भृश',
    nameEn: 'Bhrisha',
    startDeg: 135,
    endDeg: 146.25,
    centerDeg: 140.625,
    isAuspicious: false,
    zone: 'E',
    color: '#36151B',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: 'अत्यधिक सोच व क्रोध; द्वार से चोरी व हानि की आशंका',
    resultEn: 'Overthinking & anger; entrance leads to theft or losses',
    usageHi: 'रसोई स्टोव, जनरेटर, इनवर्टर',
    usageEn: 'Kitchen Stove, Generator, Inverter'
  },
  {
    code: 'E8',
    nameHi: 'अंतरिक्ष',
    nameEn: 'Antariksha',
    startDeg: 146.25,
    endDeg: 157.5,
    centerDeg: 151.875,
    isAuspicious: false,
    zone: 'E',
    color: '#36151B',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: 'चोरी व मानसिक तनाव; द्वार अशुभ',
    resultEn: 'Mental worry & theft hazard; entrance avoided',
    usageHi: 'विद्युत उपकरण, ट्रांसफार्मर',
    usageEn: 'Electrical Panels, Meter Board'
  },

  // South (S1 to S8) — Fire / Fame, Energy & Strength
  {
    code: 'S1',
    nameHi: 'अनिल',
    nameEn: 'Anila',
    startDeg: 157.5,
    endDeg: 168.75,
    centerDeg: 163.125,
    isAuspicious: false,
    zone: 'S',
    color: '#3B180C',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: 'पुत्र संतति की चिंता; द्वार से व्यापारिक स्थिरता में कमी',
    resultEn: 'Instability in business; entrance not recommended',
    usageHi: 'रसोई, गीजर, चिमनी',
    usageEn: 'Kitchen, Heater, Burner'
  },
  {
    code: 'S2',
    nameHi: 'पूषा',
    nameEn: 'Pusha',
    startDeg: 168.75,
    endDeg: 180,
    centerDeg: 174.375,
    isAuspicious: false,
    zone: 'S',
    color: '#3B180C',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: 'बंधन व नौकरी में रुकावट; द्वार से दासत्व भाव',
    resultEn: 'Career constraints & subordination; entrance avoided',
    usageHi: 'रसोई की स्लैब, पेंट्री',
    usageEn: 'Pantry, Kitchen Platform'
  },
  {
    code: 'S3*',
    nameHi: 'वितथ',
    nameEn: 'Vitatha',
    startDeg: 180,
    endDeg: 191.25,
    centerDeg: 185.625,
    isAuspicious: true,
    zone: 'S',
    color: '#065F46',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: '★ दक्षिण श्रेष्ठ द्वार — प्रभाव, बल, पराक्रम व तीव्र आर्थिक उन्नति',
    resultEn: 'Highly Auspicious — High influence, strength, vigor & rapid wealth',
    usageHi: 'मुख्य द्वार, शोरूम प्रवेश, सुरक्षा कक्ष',
    usageEn: 'Main Gate, Commercial Entrance, Security'
  },
  {
    code: 'S4*',
    nameHi: 'गृहक्षत',
    nameEn: 'Grihakshat',
    startDeg: 191.25,
    endDeg: 202.5,
    centerDeg: 196.875,
    isAuspicious: true,
    zone: 'S',
    color: '#065F46',
    element: 'Agni',
    elementNameHi: 'अग्नि तत्व',
    resultHi: '★ दक्षिण श्रेष्ठ द्वार — समृद्धि, प्रतिष्ठा, पुत्र सुख व आरोग्य',
    resultEn: 'Highly Auspicious — Family abundance, fame, health & progeny',
    usageHi: 'मुख्य द्वार, बैठक, मास्टर सुइट',
    usageEn: 'Main Entrance, Living Room, Master Bedroom'
  },
  {
    code: 'S5',
    nameHi: 'यम',
    nameEn: 'Yama',
    startDeg: 202.5,
    endDeg: 213.75,
    centerDeg: 208.125,
    isAuspicious: false,
    zone: 'S',
    color: '#28170B',
    element: 'Prithvi',
    elementNameHi: 'पृथ्वी तत्व',
    resultHi: 'ऋण व बीमारी का भय; द्वार वर्जित',
    resultEn: 'Debts & illness risk; entrance prohibited',
    usageHi: 'भारी सामान का कमरा, सीढ़ियां',
    usageEn: 'Heavy Storage, Staircase'
  },
  {
    code: 'S6',
    nameHi: 'गन्धर्व',
    nameEn: 'Gandharva',
    startDeg: 213.75,
    endDeg: 225,
    centerDeg: 219.375,
    isAuspicious: false,
    zone: 'S',
    color: '#28170B',
    element: 'Prithvi',
    elementNameHi: 'पृथ्वी तत्व',
    resultHi: 'अविवेक व धन अपव्यय; संगीत व कला हेतु उत्तम',
    resultEn: 'Sensory distractions; good for musical instruments & art',
    usageHi: 'संगीत कक्ष, व्यायाम, भंडार',
    usageEn: 'Music Room, Fitness, Storage'
  },
  {
    code: 'S7',
    nameHi: 'भृंगराज',
    nameEn: 'Bhringraj',
    startDeg: 225,
    endDeg: 236.25,
    centerDeg: 230.625,
    isAuspicious: false,
    zone: 'S',
    color: '#1C1008',
    element: 'Prithvi',
    elementNameHi: 'पृथ्वी तत्व',
    resultHi: 'अचानक हानि व मेहनत का फल न मिलना; द्वार वर्जित',
    resultEn: 'Efforts unrewarded; entrance strictly avoided',
    usageHi: 'भारी स्टोरेज, ओवरहेड वॉटर टैंक',
    usageEn: 'Heavy Storage, Overhead Tank'
  },
  {
    code: 'S8',
    nameHi: 'मृग',
    nameEn: 'Mriga',
    startDeg: 236.25,
    endDeg: 247.5,
    centerDeg: 241.875,
    isAuspicious: false,
    zone: 'S',
    color: '#1C1008',
    element: 'Prithvi',
    elementNameHi: 'पृथ्वी तत्व',
    resultHi: 'शक्ति व धन क्षय; द्वार अशुभ',
    resultEn: 'Vitality & wealth drainage; inauspicious entrance',
    usageHi: 'शौचालय सेप्टिक टैंक, कचरा स्थान',
    usageEn: 'Toilet, Waste disposal'
  },

  // West (W1 to W8) — Space/Earth / Gains, Profits & Skills
  {
    code: 'W1',
    nameHi: 'पितृ',
    nameEn: 'Pitra',
    startDeg: 247.5,
    endDeg: 258.75,
    centerDeg: 253.125,
    isAuspicious: false,
    zone: 'W',
    color: '#1E1B24',
    element: 'Prithvi',
    elementNameHi: 'पृथ्वी तत्व',
    resultHi: 'पूर्वजों का क्षेत्र; मुख्य द्वार से जीवन में संघर्ष',
    resultEn: 'Ancestral zone; entrance causes struggle in life',
    usageHi: 'मास्टर बेडरूम, भारी आलमारी',
    usageEn: 'Master Bedroom, Heavy Wardrobes'
  },
  {
    code: 'W2',
    nameHi: 'दौवारिक',
    nameEn: 'Dauvarika',
    startDeg: 258.75,
    endDeg: 270,
    centerDeg: 264.375,
    isAuspicious: false,
    zone: 'W',
    color: '#1E1B24',
    element: 'Akash',
    elementNameHi: 'आकाश तत्व',
    resultHi: 'रिश्तों में अस्थिरता; द्वार से घर में अशांति',
    resultEn: 'Unstable relationships; entrance brings insecurity',
    usageHi: 'सुरक्षा गार्ड केबिन, सीढ़ियां',
    usageEn: 'Security Cabin, Stairs'
  },
  {
    code: 'W3*',
    nameHi: 'सुग्रीव',
    nameEn: 'Sugriva',
    startDeg: 270,
    endDeg: 281.25,
    centerDeg: 275.625,
    isAuspicious: true,
    zone: 'W',
    color: '#065F46',
    element: 'Akash',
    elementNameHi: 'आकाश तत्व',
    resultHi: '★ पश्चिम श्रेष्ठ द्वार — व्यापार में अकूत लाभ, विद्या व ज्ञान वृद्धि',
    resultEn: 'Highly Auspicious — Business profits, scholarship & intelligence',
    usageHi: 'मुख्य द्वार, अध्ययन कक्ष, व्यापार कार्यालय',
    usageEn: 'Main Entrance, Study Room, Business Office'
  },
  {
    code: 'W4*',
    nameHi: 'पुष्पदंत',
    nameEn: 'Pushpadanta',
    startDeg: 281.25,
    endDeg: 292.5,
    centerDeg: 286.875,
    isAuspicious: true,
    zone: 'W',
    color: '#065F46',
    element: 'Akash',
    elementNameHi: 'आकाश तत्व',
    resultHi: '★ वरुण द्वार — वाहन, ऐश्वर्य, पदोन्नति व निरंतर धन वृद्धि',
    resultEn: 'Varuna Gate — Vehicles, luxury, career promotion & continuous income',
    usageHi: 'मुख्य द्वार, तिजोरी, ड्राइंग रूम',
    usageEn: 'Main Gate, Cash Safe, Living Room'
  },
  {
    code: 'W5',
    nameHi: 'वरुण',
    nameEn: 'Varuna',
    startDeg: 292.5,
    endDeg: 303.75,
    centerDeg: 298.125,
    isAuspicious: false,
    zone: 'W',
    color: '#17202A',
    element: 'Akash',
    elementNameHi: 'आकाश/जल तत्व',
    resultHi: 'अति-आकांक्षा व असंतोष; अध्ययन व जल हेतु उत्तम',
    resultEn: 'Restless ambitions; excellent for study & water tanks',
    usageHi: 'अध्ययन कक्ष, पानी की टंकी',
    usageEn: 'Study, Water Reservoir'
  },
  {
    code: 'W6',
    nameHi: 'असुर',
    nameEn: 'Asura',
    startDeg: 303.75,
    endDeg: 315,
    centerDeg: 309.375,
    isAuspicious: false,
    zone: 'W',
    color: '#17202A',
    element: 'Akash',
    elementNameHi: 'वायु/आकाश तत्व',
    resultHi: 'उदासी, डिप्रेशन व सरकारी परेशानियां; द्वार वर्जित',
    resultEn: 'Melancholy & regulatory issues; entrance avoided',
    usageHi: 'डंपिंग, स्टोर रूम',
    usageEn: 'Store Room, Garage'
  },
  {
    code: 'W7',
    nameHi: 'शोष',
    nameEn: 'Shosha',
    startDeg: 315,
    endDeg: 326.25,
    centerDeg: 320.625,
    isAuspicious: false,
    zone: 'W',
    color: '#111827',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: 'शारीरिक कमजोरी व व्यसन की संभावना; द्वार वर्जित',
    resultEn: 'Physical fatigue & addictive tendencies; entrance prohibited',
    usageHi: 'शौचालय, वाशिंग एरिया',
    usageEn: 'Toilet, Laundry, Washing'
  },
  {
    code: 'W8',
    nameHi: 'पापयक्ष्मा',
    nameEn: 'Papyakshma',
    startDeg: 326.25,
    endDeg: 337.5,
    centerDeg: 331.875,
    isAuspicious: false,
    zone: 'W',
    color: '#111827',
    element: 'Vayu',
    elementNameHi: 'वायु तत्व',
    resultHi: 'गंभीर रोग व असाध्य पीड़ा की आशंका; द्वार अत्यंत वर्जित',
    resultEn: 'Chronic health challenges; strictly inauspicious entrance',
    usageHi: 'शौचालय, कचरा पात्र',
    usageEn: 'Toilet, Waste bin'
  },

  // Remaining North (N1 and N2)
  {
    code: 'N1',
    nameHi: 'रोग',
    nameEn: 'Roga',
    startDeg: 337.5,
    endDeg: 348.75,
    centerDeg: 343.125,
    isAuspicious: false,
    zone: 'N',
    color: '#111827',
    element: 'Jal',
    elementNameHi: 'जल/वायु तत्व',
    resultHi: 'रोग व निर्बलता; द्वार से परिजनों में अस्वस्थता',
    resultEn: 'Sickness & low immunity; entrance causes health decline',
    usageHi: 'शौचालय, डिटॉक्स क्षेत्र',
    usageEn: 'Toilet, Detoxification'
  },
  {
    code: 'N2',
    nameHi: 'नाग',
    nameEn: 'Naga',
    startDeg: 348.75,
    endDeg: 360,
    centerDeg: 354.375,
    isAuspicious: false,
    zone: 'N',
    color: '#111827',
    element: 'Jal',
    elementNameHi: 'जल तत्व',
    resultHi: 'ईर्ष्या व पारिवारिक वैमनस्य; द्वार से विश्वासघात का भय',
    resultEn: 'Envy & mistrust; entrance causes jealousy from rivals',
    usageHi: 'अतिथियों का विश्राम, जल निकासी',
    usageEn: 'Guest seating, Drainage'
  }
];

export const get32Pada = (heading: number | null): VastuPada32 => {
  if (heading === null) {
    return VASTU_32_PADAS[0]; // Default to Mukhya (N3)
  }
  const norm = ((heading % 360) + 360) % 360;
  const match = VASTU_32_PADAS.find(p => norm >= p.startDeg && norm < p.endDeg);
  return match || VASTU_32_PADAS[0];
};
